---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: deploy2
  labels:
    app: deploy2
  namespace: default
spec:
  selector:
    matchLabels:
      app: deploy2
  template:
    metadata:
      labels:
        app: deploy2
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: vol2
              mountPath: /host/boot.log
      volumes:
        - name: vol2
          hostPath:
            path: /var/log/boot.log
